name: CI/CD Pipeline for Project

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request targeting the main branch

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Temurin distribution
          java-version: '17' # Specify Java version

      # Step 3: Install dependencies and build
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Run tests
      - name: Run Tests
        run: mvn test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' # Deploy only on main branch

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy (Customize with your deployment steps)
      - name: Deploy to Server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} # Use secrets for sensitive data
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
